inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/**

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  Exclude:
   - 'config/initializers/devise.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'config/initializers/required_form_field.rb'
    - 'spec/support/share_db_connection.rb'

Style/ClassVars:
  Exclude:
    - 'spec/support/share_db_connection.rb'

Style/WordArray:
  EnforcedStyle: brackets
